app/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('cadastro/', CadastroView.as_view(), name='cadastro'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='app/logout.html'), name='logout'),
    
    path('despesas/', despesas, name='despesas'),
    path('despesas/add/', DespesaCreateView.as_view(), name='add_despesa'),
    path('despesas/<slug:slug>/', DespesaUpdateView.as_view(), name='update_despesa'),
    path('despesas/<slug:slug>/delete/', DespesaDeleteView.as_view(), name='delete_despesa'),
    
    path('entradas/', entradas, name='entradas'),
    path('entradas/add/', EntradaCreateView.as_view(), name='add_entrada'),
    path('entradas/<slug:slug>/', EntradaUpdateView.as_view(), name='update_entrada'),
    path('entradas/<slug:slug>/delete/', EntradaDeleteView.as_view(), name='delete_entrada'),
    
    path('transacoes/', transacoes, name='transacoes'),
    path('transacoes/add/', TransacaoCreateView.as_view(), name='add_transacao'),
    path('transacoes/<slug:slug>/', TransacaoUpdateView.as_view(), name='update_transacao'),
    path('transacoes/<slug:slug>/delete/', TransacaoDeleteView.as_view(), name='delete_transacao'),
    
    path('metas_financeiras/', metas_financeiras, name='metas_financeiras'),
    path('metas_financeiras/add/', MetaFinanceiraCreateView.as_view(), name='add_meta_financeira'),
    path('metas_financeiras/<slug:slug>/', MetaFinanceiraUpdateView.as_view(), name='update_meta_financeira'),
    path('metas_financeiras/update_value/<slug:slug>/', MetaFinanceiraUpdateValueView.as_view(), name='update_valor_meta_financeira'),
    path('metas_financeiras/<slug:slug>/delete/', MetaFinanceiraDeleteView.as_view(), name='delete_meta_financeira'),
    
    path('categorias/', categorias, name='categorias'),
    path('categorias/add/', CategoriaCreateView.as_view(), name='add_categoria'),
    path('categorias/<slug:slug>/', CategoriaUpdateView.as_view(), name='update_categoria'),
    path('categorias/<slug:slug>/delete/', CategoriaDeleteView.as_view(), name='delete_categoria'),
    
    path('relatorio_mensal/', relatorio_mensal, name='relatorio_mensal'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Create your models here.
class Categoria(models.Model):
    tipos_despesa = {
        'Entrada': 'Entrada',
        'Despesa': 'Despesa'
    }
    nome = models.CharField(max_length=64, verbose_name='Nome')
    tipo = models.CharField(choices=tipos_despesa, verbose_name='Tipo')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    def get_absolute_url(self):
        return reverse('categorias')
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.nome}-{self.usuario.id}')

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.nome

class Despesa(models.Model):
    nome = models.CharField(max_length=64, verbose_name='Nome')
    valor = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Valor')
    data = models.DateField(verbose_name='Data')
    observacoes = models.TextField(blank=True, verbose_name='Observações')
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, verbose_name='Categoria')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    def get_absolute_url(self):
        return reverse('despesas')
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.nome}-{self.usuario.id}')

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.nome

class Entrada(models.Model):
    nome = models.CharField(max_length=64, verbose_name='Nome')
    valor = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Valor')
    data = models.DateField(verbose_name='Data')
    observacoes = models.TextField(blank=True, verbose_name='Observações')
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, verbose_name='Categoria')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    
    def get_absolute_url(self):
        return reverse('entradas')
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.nome}-{self.usuario.id}')

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.nome

class Transacao(models.Model):
    nome = models.CharField(max_length=64, verbose_name='Nome')
    valor = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Valor')
    data = models.DateField(verbose_name='Data')
    observacoes = models.TextField(blank=True, verbose_name='Observações')
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, verbose_name='Categoria')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    
    def get_absolute_url(self):
        return reverse('transacoes')
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.nome}-{self.usuario.id}')

        return super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Transações'

    def __str__(self):
        return self.nome

class MetaFinanceira(models.Model):
    nome = models.CharField(max_length=64, verbose_name='Nome')
    valor_total = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Valor total')
    meta_valor_mes = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Meta de valor por mês')
    valor_guardar_mes = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True, verbose_name='Valor a guardar no mês')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    
    def get_absolute_url(self):
        return reverse('metas_financeiras')
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f'{self.nome}-{self.usuario.id}')

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.nome

app/templates/app/add_categoria.html
{% extends 'app/base.html' %}

{% block title %}Adicionar categoria{% endblock %}

{% block form_title %}Adicionar categoria{% endblock %}

{% block form_classes %}col-6 offset-md-3 mt-3{% endblock %}

{% block form_submit %}Adicionar categoria{% endblock%}

{% block table %}
    {% comment %}{% endcomment %}
{% endblock %}

app/templates/app/add_despesa.html
{% extends 'app/base.html' %}

{% block title %}Adicionar despesa{% endblock%}

{% block form_title %}Adicionar despesa{% endblock %}

{% block form_classes %}col-6 offset-md-3 mt-3{% endblock %}

{% block form_submit %}Adicionar despesa{% endblock%}

{% block table %}
    {% comment %}{% endcomment %}
{% endblock %}

app/templates/app/add_meta_financeira.html
{% extends 'app/base.html' %}

{% block title %}Adicionar meta financeira{% endblock %}

{% block form_title %}Adicionar meta financeira{% endblock %}

{% block form_classes %}col-6 offset-md-3 mt-3{% endblock %}

{% block form_submit %}Adicionar meta financeira{% endblock%}

{% block table %}
    {% comment %}{% endcomment %}
{% endblock %}

app/templates/app/add_valor_meta_financeira.html
{% extends 'app/base.html' %}

{% block title %}Adicionar valor a guardar para a meta{% endblock %}

{% block form_title %}Adicionar valor a guardar para a meta{% endblock %}

{% block form_classes %}col-6 offset-md-3 mt-3{% endblock %}

{% block form_submit %}Adicionar valor{% endblock %}

{% block table %}
    {% comment %}{% endcomment %}
{% endblock %}

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body style="height: 100vh;">
        <header class="d-flex flex-column justify-content-center align-items-center">
            {% block account_buttons %}
                <div class="d-flex align-items-center justify-content-end" style="gap: 10px; height: 70px; width: 100%;">
                    <a href="" class="btn btn-primary btn-lg">Meu perfil</a>
                    <form action="{% url 'logout' %}" method="post" class="me-1">
                        {% csrf_token %}
                        <input type="submit" value="Logout" class="btn btn-danger btn-lg">
                    </form>
                </div>
                <div class="container-fluid bg-light" style="height: 20px;"></div>
            {% endblock %}
                
                <div class="d-flex justify-content-center align-items-center" style="height: 100px; width: 100%;">
                    <h1>Money Mate - Gerenciador de finanças</h1>
                </div>
            {% block nav %}
                <nav class="navbar navbar-expand-lg border-top border-dark d-flex justify-content-center">
                    <ul class="navbar-nav">
                        <li class="nav-item border-end border-white"><a class="nav-link text-light" href="{% url 'index' %}">Página inicial</a></li>
                        <li class="nav-item border-end border-white"><a class="nav-link text-light" href="{% url 'despesas' %}">Gerenciar despesas</a></li>
                        <li class="nav-item border-end border-white"><a class="nav-link text-light" href="{% url 'entradas' %}">Gerenciar entradas</a></li>
                        <li class="nav-item border-end border-white"><a class="nav-link text-light" href="{% url 'transacoes' %}">Gerenciar transações</a></li>
                        <li class="nav-item border-end border-white"><a class="nav-link text-light" href="{% url 'metas_financeiras' %}">Gerenciar metas financeiras</a></li>
                        <li class="nav-item border-end border-white"><a class="nav-link text-light" href="{% url 'categorias' %}">Gerenciar categorias</a></li>
                        <li class="nav-item border-end border-white"><a class="nav-link text-light" href="{% url 'relatorio_mensal' %}">Consultar relatórios mensais</a></li>
                    </ul>
                </nav>
            {% endblock %}
        </header>

        <main>
            {% block index %}{% endblock %}
            
            {% block form %}
                <h3 class="text-center mt-3">{% block form_title %}{% endblock %}</h3>
                <form method="post" class="{% block form_classes %}{% endblock %}" style="{% block style %}{% endblock %}">
                        {% csrf_token %}
                        {% for form_field in form %}
                            <div class="col">
                                {% if form_field.name == 'data' %}
                                    <div class="input-group mb-3">
                                        <div class="form-floating">
                                            {{ form_field }}
                                            <label for="{{ form_field.id_for_label }}">{{ form_field.label }}</label>
                                        </div>
                                        <button type="button" id="botaoHoje" class="input-group-text btn btn-dark">Hoje</button>
                                    </div>
                                {% else %}
                                    <div class="form-floating mb-3">
                                        {{ form_field }}
                                        <label for="{{ form_field.id_for_label }}">{{ form_field.label }}</label>
                                    </div>
                                {% endif %}
                                {% if form_field.help_text %}
                                <small class="form-text text-muted">{{ form_field.help_text }}</small>
                                {% endif %}
                                {% for error in form_field.errors %}
                                <div class="alert alert-danger">{{ error }}</div>
                                {% endfor %}
                            </div>
                            {% endfor %}
                            <div style="margin-top: 6px;">
                                <input type="submit" class="btn btn-primary" value="{% block form_submit %}{% endblock %}">
                            </div>
                        </form>
                    {% endblock %}
                    
                    {% block table %}
                        <h2 class="mt-2 mb-3 text-center">{% block table_title %}{% endblock %}</h2>
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    {% block table_header %}{% endblock %}
                                    {% for field_name in field_names %}
                                        <th>{{ field_name }}</th>
                                    {% endfor %}
                                    {% block update_meta_financeira %}
                                    {% endblock %}
                                    {% block table_actions %}
                                        <th>Edição</th>
                                        <th>Exclusão</th>
                                    {% endblock %}
                                 </tr>
                            </thead>
                            <tbody>
                                {% block table_content %}{% endblock %}
                            </tbody>
                        </table>
                    {% endblock %}
                {% block cadastro %}{% endblock %}
        </main>

        <footer class="d-flex justify-content-center align-items-center mt-3" style="position: relative; bottom: 0;">
            <h3>Desenvolvido por André Torres Moraes Silva<sup>&copy;</sup></h3>
        </footer>

        <script>
            let inputs = document.querySelectorAll('input');
            for (let input of inputs) {
                input.classList.add('form-control');
            }
            
            let textarea = document.querySelector('textarea');
            if (textarea) {
                textarea.classList.add('form-control');
            }

            let select = document.querySelector('select');
            if (select) {
                select.classList.add('form-select');
            }

            document.querySelector('#botaoHoje').addEventListener('click', () => {
                const hoje = new Date().toISOString().split('T')[0];
                document.querySelector('#id_data').value = hoje;
            })
        </script>
        {% block script %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

app/templates/app/cadastro.html
{% extends 'app/base.html' %}

{% block title %}Cadastro{% endblock %}

{% block account_buttons %}
    {% comment %}
    {% endcomment %}
{% endblock %}

{% block form_title %}Cadastro{% endblock %}

{% block nav %}
    {% comment %}
    {% endcomment %}
{% endblock %}

{% block form_classes %}col-6 offset-md-3 mt-3{% endblock %}

{% block form_submit %}Cadastrar-se{% endblock %}

{% block table %}
    {% comment %}
    {% endcomment %}
{% endblock %}

app/templates/app/delete_categoria.html
{% extends 'app/base.html' %}

{% block title %}Excluir categoria{% endblock %}

{% block form_title %}Excluir categoria{% endblock %}

{% block form_submit %}Excluir categoria{% endblock %}

{% block table %}
    {% comment %}{% endcomment %}
{% endblock %}

app/templates/app/delete_despesa.html
{% extends 'app/base.html' %}

{% block title %}Excluir despesa{% endblock %}

{% block form_title %}Excluir despesa{% endblock %}

{% block form_submit %}Excluir despesa{% endblock %}

{% block table %}
    {% comment %}{% endcomment %}
{% endblock %}

app/templates/app/delete_entrada.html
{% extends 'app/base.html' %}

{% block title %}Excluir entrada{% endblock %}

{% block form_title %}Excluir entrada{% endblock %}

{% block button %}Excluir entrada{% endblock %}

{% block table %}
    {% comment %}{% endcomment %}
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% load static %}

{% block title %}Money Mate{% endblock %}

{% block nav %}
    {% comment %}
    {% endcomment %}
{% endblock %}

{% block index %}
    <div class="mt-3 px-2 py-2 greeting-card" style="width: fit-content;">
        <h2>Bem vindo, {{request.user.first_name}}!</h2>
    </div>
    <div class="my-3  dollar-exchange-rate d-flex justify-content-center align-items-center" style="height: 60px;">
        <h2>Cotação atual do dólar: {{ cotacao_dolar|floatformat:2 }}</h2>
    </div>

    <div class="container mb-3">
        <div class="row ms-3">
            <div class="card me-3 mb-2 pt-1" style="width: 18rem;">
                <img src="{% static 'despesa.png' %}" alt="" class="card-img-top mt-2">
                <div class="card-body">
                    <h5 class="card-title">Gerenciar despesas</h5>
                    <p class="card-text">Controle e registre suas despesas diárias.</p>
                    <a href="{% url 'despesas' %}" class="btn btn-primary">Acessar despesas</a>
                </div>
            </div>
            <div class="card me-3 mb-2 pt-2" style="width: 18rem;">
                <img src="{% static 'entrada.png' %}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">Gerenciar entradas</h5>
                    <p class="card-text">Acompanhe todas as fontes de receita.</p>
                    <a href="{% url 'entradas' %}" class="btn btn-primary">Acessar entradas</a>
                </div>
            </div>
            <div class="card me-3 mb-2 pt-2" style="width: 18rem;">
                <img src="{% static 'transacao.png' %}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">Gerenciar transações</h5>
                    <p class="card-text">Organize e visualize todas as movimentações financeiras.</p>
                    <a href="{% url 'transacoes' %}" class="btn btn-primary">Acessar transações</a>
                </div>
            </div>
            <div class="card me-3 mb-2 pt-1" style="width: 20rem;">
                <img src="{% static 'meta.png' %}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">Gerenciar metas financeiras</h5>
                    <p class="card-text">Classifique despesas e receitas em categorias específicas.</p>
                    <a href="{% url 'metas_financeiras' %}" class="btn btn-primary">Acessar metas financeiras</a>
                </div>
            </div>
            <div class="card me-3 mb-2 pt-2" style="width: 18rem;">
                <img src="{% static 'categoria.png' %}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">Gerenciar categorias</h5>
                    <p class="card-text">Estabeleça e acompanhe seus objetivos financeiros.</p>
                    <a href="{% url 'categorias' %}" class="btn btn-primary">Acessar categorias</a>
                </div>
            </div>
            <div class="card me-3 mb-2 pt-2" style="width: 18rem;">
                <img src="{% static 'relatorio.png' %}" alt="" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">Relatórios mensais</h5>
                    <p class="card-text">Visualize relatórios financeiros detalhados mensalmente.</p>
                    <a href="{% url 'relatorio_mensal' %}" class="btn btn-primary">Acessar relatórios</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block form %}
    {% comment %}{% endcomment %}
{% endblock %}

{% block table %}
    {% comment %}{% endcomment %}
{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}

{% block title %}Login{% endblock %}

{% block account_buttons %}
    {% comment %}
    {% endcomment %}
{% endblock %}

{% block form_title %}Login{% endblock %}

{% block nav %}
    {% comment %}
    {% endcomment %}
{% endblock %}

{% block form_classes %}col-6 offset-md-3 mt-3{% endblock %}

{% block form_submit %}Entrar{% endblock %}

{% block cadastro %}
    <div class="col-6 offset-md-3 mt-3">
        <p>Ainda não é cadastrado?</p>
        <a class="btn btn-success" href="{% url 'cadastro' %}">Cadastre-se</a>
    </div>
{% endblock %}

{% block table %}
    {% comment %}
    {% endcomment %}
{% endblock %}

app/templates/app/metas_financeiras.html
{% extends 'app/base.html' %}

{% block title %}Consultar metas financeiras{% endblock %}

{% block table_title %}Metas Financeiras{% endblock %}

{% block update_meta_financeira %}
    <th>Edição</th>
{% endblock %}

{% block table_content %}
    {% for meta_financeira in metas_financeiras %}
        <tr>
            <td>{{ meta_financeira.nome }}</td>
            <td>{{ meta_financeira.valor_total }}</td>
            <td>{{ meta_financeira.meta_valor_mes }}</td>
            {% if meta_financeira.valor_guardar_mes %}
                <td>{{ meta_financeira.valor_guardar_mes }}</td>
            {% else %}
                <td>Valor não definido</td>
            {% endif %}
            <td><a href="{% url 'update_meta_financeira' meta_financeira.slug %}" class="btn btn-warning">Editar</a></td>
            <td><a href="{% url 'update_valor_meta_financeira' meta_financeira.slug %}" class="btn btn-warning">Editar valor a guardar para o mês</a></td>
            <td><a href="{% url 'delete_meta_financeira' meta_financeira.slug %}" class="btn btn-danger">Excluir</a></td>
        </tr>

        {% empty %}
            <p>Não há metas financeiras cadastradas.</p>
    {% endfor %}
    <tr>
        <td colspan="7"><a href="{% url 'add_meta_financeira' %}">Adicionar meta financeira</a></td>
    </tr>
{% endblock %}

{% block form_classes %}row row-cols-lg-auto g-4 align-items-center justify-content-center mt-1{% endblock %}
{% block style %}width: 100%;{% endblock %}

{% block form_submit %}Filtrar{% endblock %}

{% block script %}
    <script>
        document.querySelector('#id_nome').required = false;
    </script>
{% endblock %}

app/templates/app/update_entrada.html
{% extends 'app/base.html' %}

{% block title %}Editar entrada{% endblock %}

{% block form_title %}Editar entrada{% endblock %}

{% block form_classes %}col-6 offset-md-3 mt-3{% endblock %}

{% block form_submit %}Atualizar entrada{% endblock %}

{% block table %}
    {% comment %}{% endcomment %}
{% endblock %}

app/templates/app/update_valor_meta_financeira.html
{% extends 'app/base.html' %}

{% block title %}Editar valor a guardar{% endblock %}

{% block form_title %}Editar valor a guardar{% endblock %}

{% block form_classes %}col-6 offset-md-3 mt-3{% endblock %}

{% block form_submit %}Editar valor{% endblock%}

{% block table %}
    {% comment %}{% endcomment %}
{% endblock %}